## Multivariate Linear Regression

### Advertising Sales prediction

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline
import seaborn as sns

In [2]:
class LinearRegression:
    def __init__(self):
        self.min_change= 0.001
        
    def hyp(self, X, t):
        return np.dot(X, t)
        
    def cost(self, t):
        return sum((np.dot(self.X, t) - self.y)**2) / 2.0 * self.m
    
    #Not working properly
    def fscale(self, arr):
        if(arr.ndim == 1):
            return arr / (max(arr) - min(arr))
        else:
            ans= np.ones(arr.shape)
            n= arr.shape[1]
            for i in range(n):
                ans[:,i]= arr[:,i] / (max(arr[:,i]) - min(arr[:,i]))
            return ans
        
    def fit(self, XX, yy, alpha= 0.0001):
        (self.m, self.n)= XX.shape
        self.alpha= alpha
        self.X= XX.values
        self.y= yy.values
        self.X= self.fscale(XX.values)
        self.y= self.fscale(yy.values)
        self.t= np.ones(self.n)
        self.c= self.cost(self.t)
        change= self.min_change + 1
        iteration= 0
        while(change > self.min_change):
            #======================================
            hyp= np.dot(self.X, self.t)
            ans= hyp - self.y
            ans= np.dot(ans, self.X)
            self.t= self.t - self.alpha * ans / self.m
            cc= self.cost(self.t)
            #======================================
            change= self.c-cc
            self.c= cc
            if(iteration % 50 == 0):
                print("{} Cost: {}, t: {}".format(iteration, self.c, self.t))
            iteration+= 1
        print("\nOptimization Finished")
        print("Final Cost: {}, t: {}".format(self.c, self.t))
            
    def predict(self, X):
        return self.hyp(X, self.t)
    
    def rmse(self, y_true, y_pred):
        return np.sqrt(sum((y_true - y_pred)**2)/ y_true.shape[0])
    

### Demo Dataset

In [3]:
a= np.random.randint(1, 25, 500)
b= np.random.randint(100, 1000, 500)
c= 2 * a + 5 * b
data= pd.DataFrame({"TV":a, "Radio":b, "Sales":c})
X= data[['TV','Radio']]
y= data['Sales']
data.head(2)

TV  Radio  Sales
0  11    970   4872
1  18    803   4051

In [4]:
from sklearn.linear_model import LinearRegression as LR
lr= LR()
lr.fit(X, y)
lr.coef_

array([2., 5.])

In [5]:
linreg= LinearRegression()
linreg.fit(X, y, alpha= 0.03)

0 Cost: 44935.087040842125, t: [0.98870821 0.9901338 ]
50 Cost: 8580.904337874863, t: [0.6305687  0.72214455]
100 Cost: 3949.504365875801, t: [0.47791151 0.67064447]
150 Cost: 2758.186998154108, t: [0.39553302 0.68387827]
200 Cost: 2084.9789513045316, t: [0.33975972 0.71403058]
250 Cost: 1593.7509334638112, t: [0.29615179 0.74633179]
300 Cost: 1220.073913677814, t: [0.25964813 0.77648171]
350 Cost: 934.1952726236966, t: [0.228233   0.80346479]
400 Cost: 715.3203276185956, t: [0.20091122 0.82726759]
450 Cost: 547.7280423433021, t: [0.17705685 0.84815713]
500 Cost: 419.40111982366443, t: [0.15620016 0.86645591]
550 Cost: 321.1398658460159, t: [0.13795497 0.88247443]
600 Cost: 245.90018813654632, t: [0.12199126 0.89649338]
650 Cost: 188.28837220530278, t: [0.10802279 0.90876128]
700 Cost: 144.17439604832884, t: [0.09579987 0.91949649]
750 Cost: 110.39585839972656, t: [0.08510427 0.92889039]
800 Cost: 84.53127521864299, t: [0.07574512 0.93711053]
850 Cost: 64.72649059187877, t: [0.06755541

### Advertising Dataset

In [6]:
data= pd.read_csv('Files/Advertising.csv', index_col= 0)
data.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [7]:
#sns.pairplot(data)

In [8]:
feature_cols= ['TV', 'Radio', 'Newspaper']
#feature_cols= ['TV', 'Radio']
target_col= 'Sales'
X= data[feature_cols]
y= data[target_col]

In [9]:
from sklearn.linear_model import LinearRegression as LR
lr= LR()
lr.fit(X, y)
lr.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

#### Train Test Split

In [ ]:
num_train= int(X.shape[0] * .7)
X_train= X.loc[:num_train, :]
y_train= y[:num_train]
X_test= X.loc[num_train:, :]
y_test= y[num_train-1:]

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

In [ ]:
linreg= LinearRegression()
linreg.fit(X_train, y_train, alpha= 0.3)

#### On training Data

In [ ]:
y_pred= linreg.predict(X_train)
linreg.rmse(y_train.values, y_pred)

#### On Testing Data

In [ ]:
y_pred= linreg.predict(X_test)
linreg.rmse(y_test.values, y_pred)

#### Training on Entire dataset

In [10]:
linreg= LinearRegression()
linreg.fit(X, y, alpha= 0.3)

0 Cost: 7921.016551212844, t: [0.88451573 0.88024931 0.92967039]
50 Cost: 216.68076926979057, t: [0.53181317 0.34009803 0.42526708]
100 Cost: 158.91764144638222, t: [0.58546072 0.35786645 0.29145985]
150 Cost: 138.5389882882741, t: [0.60574556 0.38122521 0.21043355]
200 Cost: 130.6213319228243, t: [0.61476237 0.39935572 0.16023829]
250 Cost: 127.48115594481844, t: [0.6193985  0.41174582 0.12881488]
300 Cost: 126.23064834368935, t: [0.62203095 0.41983146 0.10904997]
350 Cost: 125.73226205868333, t: [0.62361085 0.42500977 0.0965919 ]
400 Cost: 125.53360059906184, t: [0.62458544 0.42829963 0.0887321 ]

Optimization Finished
Final Cost: 125.45538437056165, t: [0.62518477 0.43034945 0.0838498 ]


### DONE

In [ ]:
class LinearRegression2:
    def __init__(self):
        self.min_change= 0.001
        
    def hyp(self, X, t):
        return np.dot(X, t)
        
    def cost(self, t):
        return sum((np.dot(self.X, t) - self.y)**2) / 2.0 * self.m
    
    #Not working properly
    def fscale(self, arr):
        if(arr.ndim == 1):
            return arr / (max(arr) - min(arr))
        else:
            ans= np.ones(arr.shape)
            n= arr.shape[1]
            for i in range(n):
                ans[:,i]= arr[:,i] / (max(arr[:,i]) - min(arr[:,i]))
            return ans
        
    def fit(self, XX, yy, alpha= 0.0001):
        (self.m, self.n)= XX.shape
        self.alpha= alpha
        self.X= XX.values
        self.y= yy.values
        self.X= self.fscale(XX.values)
        self.y= self.fscale(yy.values)
        self.t= np.ones(self.n)
        self.c= self.cost(self.t)
        change= self.min_change + 1
        iteration= 0
        while(change > self.min_change):
            tt= np.copy(self.t)
            for i in range(self.n):
                hyp= np.dot(self.X, self.t)
                ans= hyp - self.y
                ans= np.dot(ans, self.X[:,i])
                tt[i]= self.t[i] - self.alpha * (1.0/ self.m) * ans
            self.t= np.copy(tt)
            cc= self.cost(self.t)
            change= self.c-cc
            self.c= cc
            if(iteration % 50 == 0):
                print("{} Cost: {}, t: {}".format(iteration, self.c, self.t))
            iteration+= 1
        print("\nOptimization Finished")
        print("Final Cost: {}, t: {}".format(self.c, self.t))
            
    def predict(self, X):
        return self.hyp(X, self.t)
    
    def rmse(self, y_true, y_pred):
        return np.sqrt(sum((y_true - y_pred)**2)/ y_true.shape[0])
    

In [19]:
a= np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [20]:
a= np.insert(a, 0, 1, axis= 1)
print(a)

[[1 1 2 3]
 [1 4 5 6]]
