In [5]:
import torch 

In [13]:
x= torch.empty(5,3)
print(x)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [14]:
x= torch.rand(5,4)
print(x)

tensor([[0.6508, 0.2548, 0.4643, 0.7118],
        [0.3976, 0.3412, 0.5510, 0.1946],
        [0.5031, 0.9094, 0.0813, 0.8612],
        [0.3760, 0.3411, 0.0365, 0.5893],
        [0.5044, 0.2922, 0.0262, 0.4577]])


In [15]:
x= torch.zeros(5,3, dtype= torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [17]:
x= x.new_ones(5,2, dtype= torch.double)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [19]:
x= torch.randn_like(x, dtype= torch.float)
print(x)

tensor([[ 0.5537, -0.8711],
        [-0.5917, -0.0036],
        [-0.0426, -0.9899],
        [ 0.7018,  0.1112],
        [-1.7718,  1.5513]])


In [21]:
print(x.size())

torch.Size([5, 2])


In [22]:
y= torch.randn_like(x)
print(y)

tensor([[ 0.3598,  0.3837],
        [ 0.1914, -1.2996],
        [ 0.4582,  1.5762],
        [ 0.0002, -0.1979],
        [-0.0240,  1.0635]])


In [23]:
print(x+y)

tensor([[ 0.9135, -0.4874],
        [-0.4003, -1.3032],
        [ 0.4155,  0.5863],
        [ 0.7020, -0.0868],
        [-1.7958,  2.6148]])


In [25]:
print(torch.add(x, y))

tensor([[ 0.9135, -0.4874],
        [-0.4003, -1.3032],
        [ 0.4155,  0.5863],
        [ 0.7020, -0.0868],
        [-1.7958,  2.6148]])


In [26]:
result= torch.empty(5,2)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9135, -0.4874],
        [-0.4003, -1.3032],
        [ 0.4155,  0.5863],
        [ 0.7020, -0.0868],
        [-1.7958,  2.6148]])


**Post _ symbol denotes inplace operation**

In [28]:
y.add_(x)
print(y)

tensor([[ 0.9135, -0.4874],
        [-0.4003, -1.3032],
        [ 0.4155,  0.5863],
        [ 0.7020, -0.0868],
        [-1.7958,  2.6148]])


In [29]:
print(x[:3,:])

tensor([[ 0.5537, -0.8711],
        [-0.5917, -0.0036],
        [-0.0426, -0.9899]])


In [32]:
x= torch.randn(4,4)
y= x.view(16)
z= x.view(-1, 8) #-1 means take auto with other dim [16/8= 2]
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
x= torch.randn(1)
print(x)
print(x.item())

tensor([-1.5880])
-1.5880473852157593


In [35]:
a= torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [37]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [39]:
import numpy as np

In [40]:
a= np.ones(5)
b= torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [42]:
torch.cuda.is_available()

False

### AutoGrad: Automatic Differentiation