In [1]:
import torch

In [2]:
x= torch.ones(2, 2, requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y= x+ 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [4]:
print(y.grad_fn)

In [5]:
z= y* y* 3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)


In [6]:
out= z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward1>)


In [7]:
a= torch.randn(2,2)
a= (a* 3)/(a- 1)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b= (a* a).sum()
print(b.grad_fn)

False
True


In [8]:
out.backward()

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
x= torch.ones(3, 3, requires_grad= True) 
print(x)
xx= x + 5
y= xx**3
z= y.mean()
z.backward()
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])


In [11]:
x= torch.rand(2, 2, requires_grad= True)
print('x:',x)
y= torch.sin(x)
print('sin(x):',y)
print('cos(x):',torch.cos(x))

z= y.mean()
z.backward()
print('der:',x.grad * 4)

x: tensor([[0.2127, 0.8837],
        [0.6006, 0.8979]], requires_grad=True)
sin(x): tensor([[0.2111, 0.7731],
        [0.5651, 0.7820]], grad_fn=<SinBackward>)
cos(x): tensor([[0.9775, 0.6343],
        [0.8250, 0.6233]], grad_fn=<CosBackward>)
der: tensor([[0.9775, 0.6343],
        [0.8250, 0.6233]])


In [15]:
x= torch.randn(3, requires_grad= True)
print(x)

y= x* 2
print(y)
print(y.data)
print(y.data.norm())

while(y.data.norm()< 1000):
    y= y* 2
    
print(y)

tensor([ 0.1918, -0.6681,  2.1343], requires_grad=True)
tensor([ 0.3837, -1.3362,  4.2686], grad_fn=<MulBackward>)
tensor([ 0.3837, -1.3362,  4.2686])
tensor(4.4893)
tensor([  98.2154, -342.0704, 1092.7568], grad_fn=<MulBackward>)


In [17]:
gradient= torch.tensor([0.1, 1.0, 0.0001], dtype= torch.float)
y.backward(gradient)
print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])


In [18]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
