## TensorFlow: Eager Execution

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.12.0


In [3]:
tf.enable_eager_execution()

In [4]:
print(tf.add(1,2))

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
print(tf.add([[1,2],[3,4]], [[9,8],[7,6]]))

tf.Tensor(
[[10 10]
 [10 10]], shape=(2, 2), dtype=int32)


In [6]:
print(tf.square(25))

tf.Tensor(625, shape=(), dtype=int32)


In [7]:
print(tf.reduce_sum([1,2,3]))

tf.Tensor(6, shape=(), dtype=int32)


In [8]:
print(tf.reduce_sum([[1,2,3],[4,5,6],[7,8,9]]))

tf.Tensor(45, shape=(), dtype=int32)


In [9]:
print(tf.encode_base64('Hello World'))

tf.Tensor(b'SGVsbG8gV29ybGQ', shape=(), dtype=string)


In [10]:
print(tf.decode_base64(tf.encode_base64('Hello Shiva')))

tf.Tensor(b'Hello Shiva', shape=(), dtype=string)


In [11]:
print(tf.multiply(2,[1,2,3]) + 3)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [12]:
x= tf.matmul([[1]], [[2,3]])

In [14]:
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


### NumPy Compatibility

In [25]:
import numpy as np

a= np.ones((3,4))
tensor= tf.multiply(a, tf.random.uniform((3,4)))
print(tensor)

tf.Tensor(
[[0.6637428  0.2253735  0.14781058 0.6788846 ]
 [0.07110667 0.5398487  0.21601152 0.35313404]
 [0.38191843 0.30950642 0.4996022  0.0430187 ]], shape=(3, 4), dtype=float32)


In [26]:
print(np.add(tensor, 34))

[[34.663742 34.225372 34.14781  34.678886]
 [34.071106 34.53985  34.21601  34.353134]
 [34.38192  34.309505 34.499603 34.04302 ]]


In [27]:
print(tensor.numpy())

[[0.6637428  0.2253735  0.14781058 0.6788846 ]
 [0.07110667 0.5398487  0.21601152 0.35313404]
 [0.38191843 0.30950642 0.4996022  0.0430187 ]]


### GPU Acceleration

In [28]:
x= tf.random_uniform([1,4])
print('GPU available: ', tf.test.is_gpu_available())
print('is tensor x on GPU: ', x.device.endswith('GPU:0'))

GPU available:  False
is tensor x on GPU:  False


In [29]:
print(x.device)

/job:localhost/replica:0/task:0/device:CPU:0


### Datasets